### ISSUE TITLE
Bump esp-idf tag version to v4.4.4

### ISSUE THREAD

**Issue by Vollbrecht** [esp-rs/espressif-trainings#180]
A user in the matrix chat had some problems, using the wifi. The problem he encountered was a wired network state his router pushed him in. This is happening when flashing the chip -> it starts and tries to connect to a wifi -> user than starts to attach with espmonitor -> reseting the esp (nuking the current connection)-> special network refuses to connect wifi again(looking user out for some minutes). There is a "fix" in the newer version of esp-idf that presents the user here with a more clear error.

**Comment by SergioGasquez** [comment]
IMHO, if we bump version to `v4.4.4` it should be for all project, since it's a relevant change maybe we can discuss it in the next community meeting.

**Comment by SergioGasquez** [comment]
> IMHO, if we bump version to `v4.4.4` it should be for all project, since it's a relevant change maybe we can discuss it in the next community meeting.

The issue was discussed in [yesterday's meeting ](https://github.com/esp-rs/rust/discussions/174) and we've decided to update the tag, I'll create a PR to handle it!

**Comment by Vollbrecht** [comment]
> > IMHO, if we bump version to `v4.4.4` it should be for all project, since it's a relevant change maybe we can discuss it in the next community meeting.
> 
> The issue was discussed in [yesterday's meeting ](https://github.com/esp-rs/rust/discussions/174) and we've decided to update the tag, I'll create a PR to handle it!

I could not made it yesterday. Thank you for addressing it.
