### ISSUE TITLE
Runner script target doesn't want/need `flash`.

### ISSUE THREAD

**Issue by Dygear** [esp-rs/espressif-trainings#182]
In the `.cargo/config.toml` file under each intro project, the runner script is defined as `runner = "espflash flash --monitor"
`, but only works for me once I remote the `flash` part (e.g. `runner = "espflash --monitor"`). I have tried this on Linux and now this morning macOS. Once I remove that it works without problems. Should this perhaps be removed by default?

**Comment by SergioGasquez** [comment]
You are probably using espflash 1.X, update it to 2.0: `cargo install espflash@2.0.0-rc.3 --force`. Even if its a release candidate, it works better than 1.X, and we are working on the release, sorry for the inconveniences!
