### ISSUE TITLE
How to modify the configuration of SDK，such as the port port port rate

### ISSUE THREAD

**Issue by xiaguangbo** [esp-rs/espressif-trainings#239]
The port print rate for the ESP32C2 defaults to 74880 instead of the usual 115200. After Cargo Run downloads, it will be garbled when it starts printing, and the default frame rate of espflash monitor will also be garbled
There may be other things that need to be configured. What should I do?

**Comment by SergioGasquez** [comment]
Which crystal clock frequency is your ESP32-C2? Which version of `espflash` are you using?

**Comment by xiaguangbo** [comment]
> Which crystal clock frequency is your ESP32-C2? Which version of `espflash` are you using?

crystal 26M，espflash v3

**Comment by xiaguangbo** [comment]
> > Which crystal clock frequency is your ESP32-C2? Which version of `espflash` are you using?
> 
> crystal 26M，espflash v3。26 / 40 = 74880 / 115200 = 0.65 ... I remember seeing it in the ESP Docs.

Wrong, espflash before v2, just updated to v3, now the default state is not garbled! esp32c2 baud rate is still 74880, now the tool automatically adjusts the baud rate

**Comment by SergioGasquez** [comment]
Yes, 26 MHz C2 support was added in `espflash 3.0.0`, closing the issue. Feel free to reopen if needed.
